### ISSUE TITLE
MustacheNotFoundException in OSGI bundle deployment

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis-io-jena#3]
I am working on an Camel-LDP integration [here](https://github.com/ub-leipzig/camel-kafka-activitystream-dataset).  Its function is simple in that it just commits AS events to TDB.  

While it works outside of Karaf.  I am now trying to deploy the route using blueprint and have run into a problem with trellis-io-jena requiring `org/trellisldp/io/resource.mustache`.  

It throws an `com.github.mustachejava.MustacheNotFoundException:` when blueprint instantiates the bean.  I wrapped mustache to satisfy the dependency, since the library is not built for OSGI.  It seems that for some reason mustache cannot resolve bundle resources.  Any suggestion on how to resolve this?

**Comment by christopher-johnson** [comment]
I think that I understand why this is happening.  It is a limitation of the Mustache [ClasspathResolver.](https://github.com/spullara/mustache.java/blob/master/compiler/src/main/java/com/github/mustachejava/resolver/ClasspathResolver.java#L34)  It depends on its own context to resolve resources, and not the context of the implementation bundle.  

A method like this:
```java
InputStream is = this.getClass().getResourceAsStream("resource.mustache");
mf.compile(is);
```
would work, but the DefaultResolver does not provide that option.

**Comment by christopher-johnson** [comment]
BTW, I also had the same problem with the `TDBFactory.assembleDataset()`.   The assemblerFile must be a String (that is a URL). 

Since I am not going to rewrite Jena or Mustache just so that they will work in OSGI, there are two solutions:
1) use repository URIs instead of a classpath file URIs for resources.
2) do not use OSGI.

I have made [activitystream-dataset](https://hub.docker.com/r/trellisldp/activitystream-dataset/) work as a standalone non-Karaf  Camel `Main` distribution, and this is fine for development.

**Comment by acoburn** [comment]
This fix should improve the class resource resolution. I can't confirm that this works in OSGi. I am very keen on having all of this work in OSGi, but I'm waiting on rdf-commons to release 0.5 before adding any pax-exam tests.
